"""
Main entry point for the AI-powered multi-agent content generation system.

🤖 LangChain Framework + Groq LLM Integration
⚡ Real AI generation - NOT rule-based templates
📦 Batch-optimized: 3 API calls instead of 22

This system uses:
- LangChain for agent orchestration
- Groq API (llama-3.1-8b-instant) for LLM inference
- JsonOutputParser for structured AI responses
- ChatPromptTemplate for LLM prompt engineering

All questions, answers, and comparisons are generated by the LLM.
Zero hardcoded templates or if-else logic.
"""

from src.agents.orchestrator_langchain import LangChainOrchestrator
from src.agents.base_agent import AgentInput


def main():
    """
    Main execution function.
    
    Workflow:
    1. Initialize ChatGroq LLM via LangChain
    2. AI-generate 20+ questions using LLM prompts
    3. AI-generate batch answers (1 API call)
    4. AI-generate fictional competitor
    5. AI-generate 7-point comparison
    6. Output 3 JSON files with AI-generated content
    """
    
    print("="*60)
    print("LangChain Multi-Agent Content Generation System")
    print("Powered by Groq LLM (AI-Generated, Not Rule-Based)")
    print("="*60)
    
    # Raw product data (as specified in assignment)
    raw_product_data = {
        "product_name": "GlowBoost Vitamin C Serum",
        "concentration": "10% Vitamin C",
        "skin_type": "Oily, Combination",
        "key_ingredients": "Vitamin C, Hyaluronic Acid",
        "benefits": "Brightening, Fades dark spots",
        "how_to_use": "Apply 2–3 drops in the morning before sunscreen",
        "side_effects": "Mild tingling for sensitive skin",
        "price": "₹699"
    }
    
    try:
        # Create LangChain orchestrator with Groq LLM
        orchestrator = LangChainOrchestrator(output_dir="output")
        
        # Execute workflow
        input_data = AgentInput(data=raw_product_data)
        result = orchestrator(input_data)
        
        # Print final summary
        if result.success:
            print("\n" + "="*60)
            print("✅ SUCCESS!")
            print("="*60)
            print(f"\n📦 Product: {result.data['product_name']}")
            print(f"❓ Questions Generated: {result.data['questions_generated']} (AI-powered)")
            print(f"💡 Answers Generated: {result.data['answers_generated']} (AI-powered)")
            print(f"🔄 Competitor: {result.data['competitor_generated']} (AI-generated)")
            print(f"📊 Comparison Points: {result.data['comparison_points']}")
            print(f"\n📄 Pages Created:")
            for page in result.data['pages_generated']:
                print(f"   - {page}.json")
            print(f"\n🤖 Orchestration Framework: {result.data['orchestration_framework']}")
            print(f"🧠 Model: {result.data['llm_model']}")
            print(f"⚡ Generation: {result.data['generation_method']}")
            print(f"🔄 Workflow Pattern: {result.data['workflow_pattern']}")
            print(f"📊 Total LLM API Calls: {result.data['llm_calls']['total']}")
            print(f"\n📁 Output Directory: {result.data['output_directory']}/")
            print("\n" + "="*60)
        else:
            print("\n❌ FAILED!")
            print(f"Errors: {', '.join(result.errors)}")
            
    except ValueError as e:
        print("\n❌ Configuration Error!")
        print(f"{str(e)}")
        print("\nPlease ensure:")
        print("1. You have created .env file in the project root")
        print("2. Added your Groq API key: GROQ_API_KEY=your_key_here")
        print("3. Run: pip install -r requirements.txt")
    except Exception as e:
        print("\n❌ Unexpected Error!")
        print(f"Error: {str(e)}")


if __name__ == "__main__":
    main()
